import { Router } from 'express';
import healthRouter from './health';
import { apiLimiter } from '../utils/rateLimiter';
import authRoutes from '../modules/auth/auth.routes';
import userRoutes from '../modules/user/user.routes';
import categoryRoutes from '../modules/category/category.routes';
import brandRoutes from '../modules/brand/brand.routes';
import productRoutes from '../modules/product/product.routes';
import variantRoutes from '../modules/variant/variant.routes';
import uploadRoutes from '../modules/upload/upload.routes';
import supplierRoutes from '../modules/supplier/supplier.routes';
import purchaseRoutes from '../modules/purchase/purchase.routes';
import inventoryRoutes from '../modules/inventory/inventory.routes';
import inventoryItemRoutes from '../modules/inventory-item/inventory-item.routes';
import barcodeRoutes from '../modules/barcode/barcode.routes';
import customerRoutes from '../modules/customer/customer.routes';
import saleRoutes from '../modules/sale/sale.routes';
import dashboardRoutes from '../modules/dashboard/dashboard.routes';
import reportRoutes from '../modules/reports/report.routes';
import returnRoutes from '../modules/returns/return.routes';
import settingsRoutes from '../modules/settings/settings.routes';
import auditRoutes from '../modules/audit/audit.routes';
import notificationRoutes from '../modules/notifications/notification.routes';
import preferenceRoutes from '../modules/preferences/preference.routes';
import backupRoutes from '../modules/backup/backup.routes';

const router = Router();

router.use(healthRouter);
router.use(apiLimiter);
router.use(authRoutes);
router.use(userRoutes);
router.use(categoryRoutes);
router.use(brandRoutes);
router.use(productRoutes);
router.use(variantRoutes);
router.use(uploadRoutes);
router.use(supplierRoutes);
router.use(purchaseRoutes);
router.use(inventoryRoutes);
router.use(inventoryItemRoutes);
router.use(barcodeRoutes);
router.use(customerRoutes);
router.use(saleRoutes);
router.use(dashboardRoutes);
router.use(reportRoutes);
router.use(returnRoutes);
router.use(settingsRoutes);
router.use(auditRoutes);
router.use(notificationRoutes);
router.use(preferenceRoutes);
router.use(backupRoutes);

export default router;
